Blockly.Msg.XLAN_ADD = "Copy to my backpack";
Blockly.Msg.XLAN_REMOVE = "Remove from my backpack";
Blockly.Msg.XLAN_REMOVE_ALL = "Remove all blocks from my backpack";
Blockly.Msg.XLAN_REMOVE_ALL_TITLE = "Are you sure that remove all my backpack?";
Blockly.Msg.XLAN_IMPORT_FILE = "Import blocks to my backpack from backpack file";
Blockly.Msg.XLAN_IMPORT_WORKSPACE = "Import blocks to my backpack from workspace";
Blockly.Msg.XLAN_IMPORT_WORKSPACE_TITLE = "Are you sure that import blocks to my backpack from workspace?";
Blockly.Msg.XLAN_WORKSPACE_EXPORT_FILE = "Export blocks to backpack file from workspace";
Blockly.Msg.XLAN_MYBACKPACK_EXPORT_FILE = "Export all blocks to backpack file from my backpack";